### ISSUE TITLE
Recent Update gives Front Collision Error

### ISSUE THREAD

**Issue by Cx01N** [sunnyhaibin/sunnypilot#220]
### Describe the bug

I get a warning about the front collision warning on the dev-c3 branch. I wasn’t getting this before the last few updates and don’t get it on the main branch of openpilot.
![Uploading image.jpg…]()

### Which car does this affect?

Hyundai Ioniq 5

### Provide a route where the issue occurs

f2a5efadd1dbf33 | 7C2023-10-07--20-20-34

### openpilot version

0.9.4

**Comment by sunnyhaibin** [comment]
If you have `openpilot Longitudinal Control (Alpha)` toggle enabled, it is an expected behavior. This behavior is also the same in upstream stock openpilot. It is to communicate with users that FCW/AEB is disabled when openpilot longitudinal control (alpha) is enabled. The description of the toggle also mentions the behavior.

![image](https://github.com/sunnyhaibin/sunnypilot/assets/47793918/03f3a980-a499-4146-b0e1-085c442b3b30)

**Comment by Cx01N** [comment]
I appreciate the heads up, I didn't realize it was intentional. Thanks!
